version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    build: ./serverRecycleEngine
    ports:
      - "5000:5000"
    volumes:
      - ./serverRecycleEngine:/app
      - /app/node_modules
    depends_on:
      - mongodb

  frontend:
    build: ./recycleEngineclient
    ports:
      - "3000:3000"
    volumes:
      - ./recylcleEngineclient/src:/app/src
    stdin_open: true
    depends_on:
      - backend
volumes:
  data:
